@startuml
carousel.click -> carousel.slick.listeners: MBus.publish({topic: carousel.selected, value: Selection(carouselId, htmlItem})
carousel.slick.listeners -> carousel.slick.listeners: Fix Single Item carousel bug
carousel.click -> select_parts: MBus.publish({topic: carousel.selected, value: Selection(sourceCarousel, htmlItem}})
select_parts -> select_parts: getItemIdFromPart(message.value.html.getAttributes("data-part"))
select_parts -> unselected.listeners: MBus.publish(topic: carousel.unselected}
@enduml
